### ISSUE TITLE
Sporo otvaranje aplikacije

### ISSUE THREAD

**Issue by renta75** [grozdanowski/booking-for-relief-frontend#3]
Hosting nije u EU ?
Mogući pravni problemi.

**Comment by grozdanowski** [comment]
This problem was resolved. Main issue was in the way SSR was fetching the information (awaiting 5 requests for different data sets). A new API endpoint and controller was made in the backend that delivers the aggregated data for "latest entries in all categories + item tags" so now it's only one await. Therefore performance is observably drastically improved, as well as error rate declined.

Also Heroku was moved to another instance, set up in EU zone. Also a higher tier dyno and database are associated.
